#!/bin/sh /etc/rc.common
START=99
STOP=10

VHUSBD="/usr/share/virtualhere/aarch64/vhusbd"

start() {
    [ -x "$VHUSBD" ] || exit 1
    $VHUSBD -b >/dev/null 2>&1 &
}

stop() {
    killall -9 vhusbd >/dev/null 2>&1
}
